FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npx medusa build

EXPOSE 9000

CMD ["sh", "-c", "npx medusa db:migrate && cd /app/.medusa/server && npx medusa start"]
